const mongoose = require("mongoose");

/**
 * Represents a registered individual in the system.
 *
 * Each document stores:
 * - Person's name
 * - Face embedding generated by InsightFace
 * - Registration timestamp
 *
 * The embedding acts as the biometric signature
 * used during face matching and verification.
 */
const personSchema = new mongoose.Schema(
    {
        // Name provided during face registration
        name: {
            type: String,
            required: true,
            trim: true
        },

        // Numerical vector generated by the AI model
        // and used for similarity comparison
        embedding: {
            type: [Number],
            required: true
        }
    },
    {
        // Automatically manage timestamps
        timestamps: true
    }
);

module.exports = mongoose.model(
    "Person",
    personSchema
);